// Generated by CoffeeScript 1.7.1
(function() {
  var bs, col, cycleNextTab, cycleTabs, getLocally, layout, m, md12Xs12, md1Xs12, md2Xs12, md3Xs12, md4Xs12, md5Xs12, md6Xs12, md7Xs12, md8Xs12, md9Xs12, mdColXs12, mdColXs6, passThru, row, storeLocally, window, _,
    __slice = [].slice;

  _ = require('lodash');

  m = require('mithril');

  if (typeof window === "undefined" || window === null) {
    window = {
      __not_browser: true,
      localStorage: {}
    };
  }

  storeLocally = function(key, val) {
    var _ref;
    console.log("storing [" + key + "]", val);
    if (window.__not_browser) {
      return window.localStorage[key] = val;
    } else {
      return (_ref = window.localStorage) != null ? _ref[key] = JSON.stringify(val) : void 0;
    }
  };

  getLocally = function(key) {
    var v, _ref, _ref1, _ref2;
    if (window.__not_browser) {
      v = (_ref = window.localStorage[key]) != null ? _ref : null;
    } else {
      v = JSON.parse((_ref1 = (_ref2 = window.localStorage) != null ? _ref2[key] : void 0) != null ? _ref1 : null);
    }
    console.log("getting [" + key + "]", v);
    return v;
  };

  passThru = function(ctrlInstance) {
    return function() {
      return ctrlInstance;
    };
  };

  cycleNextTab = function(nextTab) {
    return m.route(nextTab);
  };

  cycleTabs = function(idList, wait) {
    var current, nextTab;
    idList = _.clone(idList);
    current = idList.shift();
    nextTab = idList[0];
    idList.push(current);
    _.delay(cycleNextTab, wait, "/" + nextTab);
    return _.delay(cycleTabs, wait * 2, idList, wait);
  };

  row = function() {
    var attrs, children, cssOrAttrs, extras, staticCss, _i;
    extras = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), children = arguments[_i++];
    if ((extras != null ? extras.length : void 0) === 2) {
      staticCss = extras[0], attrs = extras[1];
    }
    if ((extras != null ? extras.length : void 0) < 2) {
      cssOrAttrs = extras.shift();
      if (_.isString(cssOrAttrs)) {
        staticCss = cssOrAttrs;
      }
      if (_.isPlainObject(cssOrAttrs)) {
        attrs = cssOrAttrs;
      }
    }
    if (staticCss == null) {
      staticCss = '';
    }
    if (attrs == null) {
      attrs = {};
    }
    return m(".row" + staticCss, attrs, children);
  };

  col = _.curry(function(xs, md, staticCss, content) {
    content = _.isArray(content) ? content : [content];
    return m(".col-xs-" + xs + ".col-md-" + md + staticCss, content);
  });

  mdColXs12 = col(12);

  mdColXs6 = col(6);

  md1Xs12 = mdColXs12(1);

  md2Xs12 = mdColXs12(2);

  md3Xs12 = mdColXs12(3);

  md4Xs12 = mdColXs12(4);

  md5Xs12 = mdColXs12(5);

  md6Xs12 = mdColXs12(6);

  md7Xs12 = mdColXs12(7);

  md8Xs12 = mdColXs12(8);

  md9Xs12 = mdColXs12(9);

  md12Xs12 = mdColXs12(12);

  layout = function(nav, body, attrs) {
    if (attrs == null) {
      attrs = {};
    }
    return m('.layout.container-fluid', attrs, m('.row', [m('header', nav), m('main', body)]));
  };

  bs = {
    row: row,
    md1Xs12: md1Xs12,
    md2Xs12: md2Xs12,
    md3Xs12: md3Xs12,
    md4Xs12: md4Xs12,
    md5Xs12: md5Xs12,
    md6Xs12: md6Xs12,
    md7Xs12: md7Xs12,
    md8Xs12: md8Xs12,
    md9Xs12: md9Xs12,
    md12Xs12: md12Xs12
  };

  module.exports = {
    storeLocally: storeLocally,
    getLocally: getLocally,
    layout: layout,
    bs: bs,
    passThru: passThru,
    cycleTabs: cycleTabs
  };

}).call(this);
